# To launch: "sudo docker-compose up -d"
# To stop : "sudo docker-compose down"
version: "3.3"

services:
  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - 3001:80
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    restart: always
    networks:
      - backend
      - frontend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
